# fly.toml app configuration file generated for airtime-data on 2023-07-18T17:29:45+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "airtime-data"
primary_region = "jnb"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
